### ISSUE TITLE
Firestore: 504 Deadline Exceeded making single write on Firestore

### ISSUE THREAD

**Issue by amritsub** [googleapis/python-firestore#11]
resurfaced from https://github.com/firebase/firebase-admin-python/issues/308

#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
2. OS type and version: macOs Mojave 10.14.5
3. Python version and virtual environment information: **Python 3.7.4**
4. google-cloud-<service> version:  `pip show google-<service>` or `pip freeze`
**firebase-admin==2.17.0
google-api-core==1.14.2
google-api-python-client==1.7.10
google-cloud-core==1.0.3
google-cloud-firestore==1.3.0**

#### Steps to reproduce

  1. Initialize GOOGLE_APPLICATION_CREDENTIALS environment variable with the Firebase service account json file path.
2. Set up virtualenv, install firebase-admin and run it.

#### Code example

```python
import firebase_admin
from firebase_admin import firestore, credentials

firebase_admin.initialize_app()
print("initialized firebase successfully")

product_dict={
  'test1': 'test',
  'test2': 'test2'
}
firestore_client = firestore.client()
doc_ref = firestore_client.collection('products').document('test2')
doc_ref.set(product_dict)
```

#### Stack trace
```
Traceback (most recent call last):
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/grpc/_channel.py", line 565, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1564801527.004575000","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":69,"grpc_status":4}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 13, in <module>
    doc_ref.set(product_dict)
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/google/cloud/firestore_v1/document.py", line 234, in set
    write_results = batch.commit()
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/google/cloud/firestore_v1/batch.py", line 147, in commit
    metadata=self._client._rpc_metadata,
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/google/cloud/firestore_v1/gapic/firestore_client.py", line 1042, in commit
    request, retry=retry, timeout=timeout, metadata=metadata
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/google/api_core/retry.py", line 273, in retry_wrapped_func
    on_error=on_error,
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/google/api_core/retry.py", line 182, in retry_target
    return target()
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded
```

**Comment by BenWhitehead** [comment]
@crwilcox Do you know if this is expected to be addressed in some of the recent python work that has taken place?

**Comment by crwilcox** [comment]
Since this was opened a number of releases have occurred, including a few involving gRPC and the api-core modules. And the timeout was increased from 20 -> 60 seconds. Also, we have moved to a new gRPC generated later in a 2.0.0dev candidate release. 

Is this still an issue on latests 1.x release?

**Comment by skgbanga** [comment]
@crwilcox I am currently running into a similar issue with 1.9.0. (I am doing a batch commit though). 
Is there a way in which user can up this timeout value? ( I also need to investigate why I am getting the timeout in the first place, but that is a different issue)

**Comment by crwilcox** [comment]
@skgbanga while not officially supported, you could alter https://github.com/googleapis/python-firestore/blob/v1.9.0/google/cloud/firestore_v1/gapic/firestore_client_config.py in your install, or construct the transport as part of client init. Also, I believe the 2.0.0 versions have exposed timeouts at many of the method surfaces that may make this easier.

**Comment by crwilcox** [comment]
@skgbanga are you still blocked? It seems you may have moved to a slightly different issue with batch commit?

**Comment by dmahugh** [comment]
Closing this issue, but if anyone runs into the same again going forward please open a new issue with details and context. Thanks!
