### ISSUE TITLE
Firebase on Lambda ServiceUnavailable: 503 Socket closed _Rendezvous of RPC that terminated

### ISSUE THREAD

**Issue by Cosbgn** [googleapis/python-firestore#12]
Hello,
I'm running a flask app on AWS lambda. I start firebase like this:

```
if not len(firebase_admin._apps):
	cred = credentials.Certificate('creds.json')
	firebase_admin.initialize_app(cred)
db = firestore.client()
```
However today I started getting this error. Is there a particlar way I should start firebase on a serverless environment?

```
ServiceUnavailable: 503 Socket closed
  File "flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "views.py", line 210, in post
    "data":data
  File "google/cloud/firestore_v1/collection.py", line 170, in add
    metadata=self._client._rpc_metadata,
  File "google/cloud/firestore_v1/gapic/firestore_client.py", line 545, in create_document
    request, retry=retry, timeout=timeout, metadata=metadata
  File "google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "google/api_core/retry.py", line 270, in retry_wrapped_func
    on_error=on_error,
  File "google/api_core/retry.py", line 179, in retry_target
    return target()
  File "google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
    # Permission is hereby granted, free of charge, to any person obtaining a copy
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1555051727.785793445","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Socket closed","grpc_status":14}"
>
  File "google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "grpc/_channel.py", line 549, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
```

**Comment by Benny739** [comment]
Any news in this? Seeing the same error atm.

**Comment by codal-mharkhani** [comment]
@Cosbgn @schmidt-sebastian 

getting same error, is this issue resolved..?

**Comment by schmidt-sebastian** [comment]
These transient issues are hard to debug for us and will likely always occur at some rate. Our goal is to minimize these occurrences. If you can help us with a reproduction, we can open this again and one of our Python devs can see if we can mitigate this issue further.

**Comment by codal-mharkhani** [comment]
@schmidt-sebastian 

i have one python script, which is executing at every 4 minute from lambda function. it will do GET and UPDATE query on firestore. this script is worked 15 days without any issue. and suddenly started raising 503 errors randomly, like 30% it is returning 503 errors. please help me ASAP how can i resolve it

```
Deadline of 600.0s exceeded while calling functools.partial(<function _wrap_stream_errors.<locals>.error_remapped_callable at 0x7fe5a9c26840>, parent: "projects/contap-dev/databases/(default)/documents/dev_virtual_speed/3121"
structured_query {
  from {
    collection_id: "speedMembers"
  }
}
, metadata=[('google-cloud-resource-prefix', 'projects/contap-dev/databases/(default)'), ('x-goog-request-params', 'parent=projects/contap-dev/databases/%28default%29/documents/dev_virtual_speed/3121'), ('x-goog-api-client', 'gl-python/3.6.10 grpc/1.30.0 gax/1.21.0 gapic/1.8.1 gccl/1.8.1')]), last exception: 503 failed to connect to all addresses: RetryError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 255, in lambda_handler
    available_users = get_available_users(event_id, db)
  File "/var/task/lambda_function.py", line 49, in get_available_users
    available_users = [i.id for i in event_member]
  File "/var/task/lambda_function.py", line 49, in <listcomp>
    available_users = [i.id for i in event_member]
  File "/var/task/google/cloud/firestore_v1/query.py", line 859, in stream
    metadata=self._client._rpc_metadata,
  File "/var/task/google/cloud/firestore_v1/gapic/firestore_client.py", line 1311, in run_query
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/var/task/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/var/task/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/var/task/google/api_core/retry.py", line 206, in retry_target
    last_exc,
  File "<string>", line 3, in raise_from
google.api_core.exceptions.RetryError: Deadline of 600.0s exceeded while calling functools.partial(<function _wrap_stream_errors.<locals>.error_remapped_callable at 0x7fe5a9c26840>, parent: "projects/contap-dev/databases/(default)/documents/dev_virtual_speed/3121"
structured_query {
  from {
    collection_id: "speedMembers"
  }
}
, metadata=[('google-cloud-resource-prefix', 'projects/contap-dev/databases/(default)'), ('x-goog-request-params', 'parent=projects/contap-dev/databases/%28default%29/documents/dev_virtual_speed/3121'), ('x-goog-api-client', 'gl-python/3.6.10 grpc/1.30.0 gax/1.21.0 gapic/1.8.1 gccl/1.8.1')]), last exception: 503 failed to connect to all addresses
```
