### ISSUE TITLE
Error while trying to query firestore data

### ISSUE THREAD

**Issue by linux-devil** [googleapis/python-firestore#128]
#### Environment details

1. I am using python API for firestore data retreival
```
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore
from google.cloud import storage

```
2. ubuntu 18.04
3. Python 3.6.9
4.
```
Name: google-cloud-firestore
Version: 1.8.1
Summary: Google Cloud Firestore API client library
Home-page: https://github.com/googleapis/python-firestore
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /home/harshit/.local/lib/python3.6/site-packages
Requires: pytz, google-api-core, google-cloud-core
Required-by: firebase-admin
```

#### Steps to reproduce

```
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore
from google.cloud import storage

cred = credentials.Certificate('/home/<api-key>.json')
firebase_admin.initialize_app(cred, {'databaseURL' : 'https://<project>.firebaseio.com/'})
db = firestore.client()
emp_ref = db.collection('users')
docs = emp_ref.stream()
for i in docs:
    dictx = i.to_dict()
```

#### Stack trace
```
>>> db = firestore.client()
>>> emp_ref = db.collection('users').get()
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/harshit/.local/lib/python3.6/site-packages/google/cloud/firestore_v1/collection.py", line 423, in get
    return query.get(transaction=transaction)
  File "/home/harshit/.local/lib/python3.6/site-packages/google/cloud/firestore_v1/query.py", line 820, in get
    return list(result)
  File "/home/harshit/.local/lib/python3.6/site-packages/google/cloud/firestore_v1/query.py", line 859, in stream
    metadata=self._client._rpc_metadata,
  File "/home/harshit/.local/lib/python3.6/site-packages/google/cloud/firestore_v1/gapic/firestore_client.py", line 1311, in run_query
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/home/harshit/.local/lib/python3.6/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/harshit/.local/lib/python3.6/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/home/harshit/.local/lib/python3.6/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/home/harshit/.local/lib/python3.6/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/harshit/.local/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 150, in error_remapped_callable
    return _StreamingResponseIterator(result, prefetch_first_result=prefetch_first)
  File "/home/harshit/.local/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 73, in __init__
    self._stored_first_result = six.next(self._wrapped)
  File "/home/harshit/.local/lib/python3.6/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/home/harshit/.local/lib/python3.6/site-packages/grpc/_channel.py", line 697, in _next
    _common.wait(self._state.condition.wait, _response_ready)
  File "/home/harshit/.local/lib/python3.6/site-packages/grpc/_common.py", line 138, in wait
    _wait_once(wait_fn, MAXIMUM_WAIT_TIMEOUT, spin_cb)
  File "/home/harshit/.local/lib/python3.6/site-packages/grpc/_common.py", line 103, in _wait_once
    wait_fn(timeout=timeout)
  File "/usr/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)

```

Same code was running fine until today , now suddenly its taking longest to fetch documents from firestore . Appreciate any help here as its breaking my application backend. Thanks in advance.

**Comment by linux-devil** [comment]
This is a very critical piece for our service , we are unable to function and do anything in the backend since we cannot access firestore

**Comment by linux-devil** [comment]
```
Traceback (most recent call last):
  File "/home/harshit/.local/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 150, in error_remapped_callable
    return _StreamingResponseIterator(result, prefetch_first_result=prefetch_first)
  File "/home/harshit/.local/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 73, in __init__
    self._stored_first_result = six.next(self._wrapped)
  File "/home/harshit/.local/lib/python3.6/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/home/harshit/.local/lib/python3.6/site-packages/grpc/_channel.py", line 706, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1595508567.205052312","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":69,"grpc_status":4}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/harshit/.local/lib/python3.6/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/home/harshit/.local/lib/python3.6/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/harshit/.local/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 152, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "face_retreival.py", line 59, in <module>
    for i in docs:
  File "/home/harshit/.local/lib/python3.6/site-packages/google/cloud/firestore_v1/query.py", line 859, in stream
    metadata=self._client._rpc_metadata,
  File "/home/harshit/.local/lib/python3.6/site-packages/google/cloud/firestore_v1/gapic/firestore_client.py", line 1311, in run_query
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/home/harshit/.local/lib/python3.6/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/harshit/.local/lib/python3.6/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/home/harshit/.local/lib/python3.6/site-packages/google/api_core/retry.py", line 206, in retry_target
    last_exc,
  File "<string>", line 3, in raise_from
google.api_core.exceptions.RetryError: Deadline of 600.0s exceeded while calling functools.partial(<function _wrap_stream_errors.<locals>.error_remapped_callable at 0x7fa5f150d0>, parent: "projects/watchmen-56/databases/(default)/documents"
structured_query {
  from {
    collection_id: "users"
  }
}
, metadata=[('google-cloud-resource-prefix', 'projects/watchmen-56/databases/(default)'), ('x-goog-request-params', 'parent=projects/watchmen-56/databases/%28default%29/documents'), ('x-goog-api-client', 'gl-python/3.6.9 grpc/1.30.0 gax/1.21.0 gapic/1.8.1 gccl/1.8.1')]), last exception: 504 Deadline Exceeded
```

**Comment by linux-devil** [comment]
Any pointers?

**Comment by HemangChothani** [comment]
@linux-devil I think you are using an older version of firestore.
The traceback you report is due to the back-end not replying to the CollectionReference.stream request within 60 seconds.

Although implicit retries are disabled by default for non-idempotent operations, you can add explicit support at the application level, e.g.:

```python
from google.api_core import exceptions
from google.api_core import retry


# Could include other retriable exception types
predicate_504 = retry.if_exception_type(exceptions.DeadlineExceeded)

# Could configure deadline, etc.
retry_504 = retry.Retry(predicate_504)

retry_504(doc_ref.set)(product_dict)

**Comment by HemangChothani** [comment]
Issue is also related to the https://github.com/googleapis/python-firestore/issues/11

**Comment by tseaver** [comment]
@linux-devil Your example shows using `emp_ref.stream()`, while the traceback part shows `emp_ref.get()`.  One difference between those two methods is that `get()` fetches the whole collection into memory as a list, after calling `stream()` to get the iterator.  Can you retry using `stream()` instead, e.g.:

```python
>>> db = firestore.client()
>>> emp_ref = db.collection('users')
>>> for doc_snapshot in emp_ref.stream():
...     do_something_with(doc_snapshot.to_dict())
```
