### ISSUE TITLE
Implement retry with exponential backoff algorithm

### ISSUE THREAD

**Issue by tomoaki241** [googleapis/python-firestore#25]
python-firestore doesn't allow users change default GRPC timeout values. The current timeout values are too long, and not practical.

For instance, collections method doesn't pass timeout parameter
https://github.com/tseaver/google-cloud-python/blob/master/firestore/google/cloud/firestore_v1/client.py#L454

even though list_collection_ids can accept it.
https://github.com/tseaver/google-cloud-python/blob/master/firestore/google/cloud/firestore_v1/gapic/firestore_client.py#L1357

Moreover, even if you directly use firestore_v1/gapic/firestore_client.py and specify the timeout, the behavior is not practical.

Let's say gRPC server has 5 second latency, and you set 3 seconds as timeout value when using get_document.
https://github.com/tseaver/google-cloud-python/blob/master/firestore/google/cloud/firestore_v1/gapic/firestore_client.py#L253

Then, the call ends up with a Deadline Exceeded error after 10 minutes after repetitive 3 second timeout events.

google.api_core.exceptions.RetryError: Deadline of 600.0s exceeded while calling functools.partial(<function _wrap_unary_errors.<locals>.error_remapped_callable at 0x7fa431ea3950>, name: "***"
, metadata=[('x-goog-request-params', 'name=***'), ('x-goog-api-client', 'gl-python/3.7.4 grpc/1.27.2 gax/1.16.0 gapic/1.6.
2 gccl/1.6.2')]), last exception: 504 Deadline Exceeded

**Comment by crwilcox** [comment]
We can look into exposing the retry settings to the client level method. 

Are you certain it isn't being backed of exponentially by default? This is the underlying retry. https://github.com/googleapis/python-api-core/blob/5e5559202891f7e5b6c22c2cbc549e1ec26eb857/google/api_core/retry.py#L221

**Comment by tomoaki241** [comment]
I think the issue is not only the exponential backoff, but also not being able to configure the retry object. Here's what I confirmed.

from google.cloud import firestore
db = firestore.Client()
doc_ref = db._firestore_api.get_document("projects/dummy-project-id/databases/(default)/documents/users/user1", timeout=0.2)

This gRPC call continues if the server latency exceeds the value (0.2 in this case) because the RPC call continuously use 0.2 for all retries without exponential backoff algorithm until the total time reaches 10 mins and the script ends up with 504 Deadline Exceeded [1]. If it uses exponential backoff algorithm, the call will succeed as soon as the retry timeout exceeds the server side latency, and won't end up with 504 Deadline Exceeded nor have to wait for 10 mins.

<504 Deadline Exceeded error>
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    db._firestore_api.get_document("projects/dummy-project-id/databases/(default)/documents/users/user1", timeout=0.2)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/firestore_v1/gapic/firestore_client.py", line 335, in get_document
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/usr/local/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 206, in retry_target
    last_exc,
  File "<string>", line 3, in raise_from
google.api_core.exceptions.RetryError: Deadline of 600.0s exceeded while calling functools.partial(<function _wrap_unary_errors.<locals>.error_remapped_callable at 0x7fa431ea3950>, name: "projects/dummy-project-id/databases/(default)/documents/users/user1", metadata=[('x-goog-request-params', 'name=projects/dummy-project-id/databases/%28default%29/documents/users/user1'), ('x-goog-api-client', 'gl-python/3.7.4 grpc/1.27.2 gax/1.16.0 gapic/1.6.2 gccl/1.6.2')]), last exception: 504 Deadline Exceeded
</504 Deadline Exceeded error>

In addition to the timeout parameter, methods in google-cloud-firestore should accept a retry object.
Because you cannot directly set the timeout and retry parameters when using the exposed methods, users need to call an internal method, which is not ideal.

from google.cloud import firestore
db = firestore.Client()
doc_ref = db._firestore_api.get_document("projects/dummy-project-id/databases/(default)/documents/users/user1", timeout=0.2, retry=retry.Retry(initial=1.0, maximum=10.0, deadline=20.0))

**Comment by 747project** [comment]
@crwilcox If I understand correctly, it appears that the transactional decorator may not expose or nor allow retry configuration: https://github.com/googleapis/python-firestore/blob/v2.0.2/google/cloud/firestore_v1/transaction.py#L361

**Comment by meredithslota** [comment]
We updated retry handling in v2.0 which was released in late 2020, and there have been a handful of small improvements since then in 2.0+ versions. If there are still improvements needed here, please open a new issue. Thanks!
