### ISSUE TITLE
Add support to run emulator for system tests.

### ISSUE THREAD

**Issue by crwilcox** [googleapis/python-firestore#287]
Currently the system tests do not run with the emulator.

```
ERROR    grpc._plugin_wrapping:_plugin_wrapping.py:82 AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x11169b310>" raised exception!
Traceback (most recent call last):
  File "/Users/crwilcox/workspace/python-firestore/.nox/system-3-7/lib/python3.7/site-packages/grpc/_plugin_wrapping.py", line 78, in __call__
    context, _AuthMetadataPluginCallback(callback_state, callback))
  File "/Users/crwilcox/workspace/python-firestore/.nox/system-3-7/lib/python3.7/site-packages/google/auth/transport/grpc.py", line 86, in __call__
    callback(self._get_authorization_headers(context), None)
  File "/Users/crwilcox/workspace/python-firestore/.nox/system-3-7/lib/python3.7/site-packages/google/auth/transport/grpc.py", line 73, in _get_authorization_headers
    self._request, context.method_name, context.service_url, headers
  File "/Users/crwilcox/workspace/python-firestore/.nox/system-3-7/lib/python3.7/site-packages/google/auth/credentials.py", line 134, in before_request
    self.apply(headers)
  File "/Users/crwilcox/workspace/python-firestore/.nox/system-3-7/lib/python3.7/site-packages/google/auth/credentials.py", line 112, in apply
    if self.quota_project_id:
  File "/Users/crwilcox/workspace/python-firestore/.nox/system-3-7/lib/python3.7/site-packages/google/auth/credentials.py", line 83, in quota_project_id
    return self._quota_project_id
AttributeError: 'EmulatorCreds' object has no attribute '_quota_project_id'
```

**Comment by tseaver** [comment]
@crwilcox Did PR #402 resolve this issue?

**Comment by crwilcox** [comment]
```
❯ gcloud beta firestore emulator
❯ export FIRESTORE_EMULATOR_HOST=127.0.0.1:1234
❯ nox -s system-3.7
```

Seems mostly good locally. though some tests don't seem to work with the emulator (Partition Query)

**Comment by tseaver** [comment]
@crwilcox 
> gcloud beta firestore emulator

Hmm, that doesn't work for me -- I need to run `gcloud beta emulators firestore start`.  I'm running with updated components, I think.

And the tests don't pass at that point, either.  The fail with `503 failed to connect to all addresses`.

**Comment by crwilcox** [comment]
That was a typo ;)

**Comment by tseaver** [comment]
Oddly, the systests still want a `GCLOUD_PROJECT` to be set in the environment, even under the emulator.
