### ISSUE TITLE
ImportError: No module named '_socket'

### ISSUE THREAD

**Issue by dominic-ks** [googleapis/python-firestore#317]
#### Environment details

  - OS type and version: Ubuntu 18.4
  - Python version: `python --version` 3.7.5
  - pip version: `pip --version` 20.0.1
  - `google-cloud-firestore` version: `pip show google-cloud-firestore` 2.0.2

#### Steps to reproduce

  1. Install firebase admin using the instructions here - https://firebase.google.com/docs/firestore/quickstart
  2. Attempt to import firebase admin using a Service Account

#### Code example

```import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore

# Use a service account
cred = credentials.Certificate('my-firebase-key.json')
firebase_admin.initialize_app(cred)

db = firestore.client()
```

#### Stack trace
```
Traceback (most recent call last):
  File "z:\servers\geserver\gesource\python/ges\GamePlayManager.py", line 46, in LoadScenario
    scenario = getattr( sys.modules[module], scenario_name )()
KeyError: 'GamePlay.LTKHeadShots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "z:\servers\geserver\gesource\python/ges\GamePlayManager.py", line 50, in LoadScenario
    __import__( module, globals(), locals() )
  File "z:\servers\geserver\gesource\python/ges\GamePlay\LTKHeadShots.py", line 23, in <module>
    import firebase_admin
  File "z:\servers\geserver\gesource\python/lib\firebase_admin\__init__.py", line 21, in <module>
    from firebase_admin import credentials
  File "z:\servers\geserver\gesource\python/lib\firebase_admin\credentials.py", line 19, in <module>
    import google.auth
  File "z:\servers\geserver\gesource\python/lib\google\auth\__init__.py", line 19, in <module>
    from google.auth._default import default, load_credentials_from_file
  File "z:\servers\geserver\gesource\python/lib\google\auth\_default.py", line 30, in <module>
    import google.auth.transport._http_client
  File "z:\servers\geserver\gesource\python/lib\google\auth\transport\__init__.py", line 30, in <module>
    from six.moves import http_client
  File "z:\servers\geserver\gesource\python/lib\six.py", line 92, in __get__
    result = self._resolve()
  File "z:\servers\geserver\gesource\python/lib\six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "z:\servers\geserver\gesource\python/lib\six.py", line 82, in _import_module
    __import__(name)
  File "z:\servers\geserver\gesource\python/lib\http\client.py", line 69, in <module>
    import email.parser
  File "z:\servers\geserver\gesource\python/lib\email\parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "z:\servers\geserver\gesource\python/lib\email\feedparser.py", line 27, in <module>
    from email import message
  File "z:\servers\geserver\gesource\python/lib\email\message.py", line 15, in <module>
    from email import utils
  File "z:\servers\geserver\gesource\python/lib\email\utils.py", line 29, in <module>
    import socket
  File "z:\servers\geserver\gesource\python/lib\socket.py", line 47, in <module>
    import _socket
ImportError: No module named '_socket'
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by craiglabenz** [comment]
Thanks for reporting this issue, @dominic-ks. I've just attempted to recreate this issue against both your library versions and updated versions; but neither yielded this error. Would you please confirm that you're still seeing the error? If so, it's possible this is a Windows-specific issue 🤔
