### ISSUE TITLE
simple collection stream() encounters Deadline Exceeded

### ISSUE THREAD

**Issue by cdg720** [googleapis/python-firestore#32]
Hi,

I have a simple line of stream() with a collection of 54k documents which is less than 4GB on memory. Sometimes it runs and sometimes it dies with 504 DeadLine Exceeded.
```
content_docs = [_ for _ in db.collection(u'contents_metadata').stream()]
```

  - OS type and version: 
I am using a Docker.
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
  - Python version: Python 3.6.9
  - pip version: pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
  - `google-cloud-firestore` version: Version: 1.6.2

#### Stack trace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/grpc_helpers.py", line 96, in next
    return six.next(self._wrapped)
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 706, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1586916036.571589731","description":"Error received from peer ipv4:172.217.5.106:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/10b/./bazel-bin/recommendation/recommendation.runfiles/__main__/recommendation/recommendation.py", line 295, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/10b/./bazel-bin/recommendation/recommendation.runfiles/__main__/recommendation/recommendation.py", line 282, in main
    content_docs = [_ for _ in db.collection(u'contents_metadata').stream()]
  File "/10b/./bazel-bin/recommendation/recommendation.runfiles/__main__/recommendation/recommendation.py", line 282, in <listcomp>
    content_docs = [_ for _ in db.collection(u'contents_metadata').stream()]
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/firestore_v1/query.py", line 775, in stream
    for response in response_iterator:
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/grpc_helpers.py", line 99, in next
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded
```

I see some other 504 issues here but they seem to be related to write.

Does anyone know of a solution?

Thanks,
DK

**Comment by cdg720** [comment]
I think it is related to https://github.com/googleapis/python-firestore/issues/19

When it times out, my binary has dependency on a proto. Once I remove the dependency, it doesn't time out.

**Comment by crwilcox** [comment]
@cdg720 we are nearing a release of a new version of the library (v2.0.0). This uses an overhauled proto layer, so it is quite possible this is no longer going to repro. If you have a chance to try that out do let us know. It is currently available as 2.0.0-dev2, but I expect in the next couple of days to GA 2.0.0.

**Comment by crwilcox** [comment]
@cdg720 is this an issue you are encountering still? v2 has since been released which has a, more or less, rewritten rpc layer.

**Comment by cdg720** [comment]
i am still using the old version with fetching chunks of documents at a time: https://stackoverflow.com/a/56012426/13161301

i am going to close this. if i encounter the problem with the newer version later, i will reopen it.

thanks
