### ISSUE TITLE
Does this library work with the local firestore emulator?

### ISSUE THREAD

**Issue by gaborfeher** [googleapis/python-firestore#33]
Pyhton==3.6
google-cloud-firestore==1.6.2

I start the emulator like this:
```
gcloud beta emulators firestore start --host-port=:8258
```
and my code like this:
```
dev_appserver.py \
  --application my-app \
  --port=18080 \
  --admin_port=8010 \
  --host 0.0.0.0 \
  --env_var FIRESTORE_EMULATOR_HOST=localhost:8258 \
  $(pwd)/app.yaml
```
Despite that, the following in my code crashes:
```
from google.cloud import firestore
db = firestore.Client(project='my-project')
```
with an exception like this:
```
INFO     2020-04-16 18:16:41,815 _metadata.py:95] Compute Engine Metadata server unavailable onattempt 1 of 3
INFO     2020-04-16 18:16:41,878 _metadata.py:95] Compute Engine Metadata server unavailable onattempt 2 of 3
INFO     2020-04-16 18:16:44,882 _metadata.py:95] Compute Engine Metadata server unavailable onattempt 3 of 3
[2020-04-16 18:16:44,883] ERROR in app: Exception on /products/create [GET]
Traceback (most recent call last):
  File "/tmp/tmpSeKi4K/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/tmp/tmpSeKi4K/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/tmp/tmpSeKi4K/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/tmp/tmpSeKi4K/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/tmp/tmpSeKi4K/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/tmp/tmpSeKi4K/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gabor/my-app/handlers/products.py", line 15, in create
    db = firestore.Client(project='my-project')
  File "/tmp/tmpSeKi4K/lib/python3.6/site-packages/google/cloud/firestore_v1/client.py", line 110, in __init__
    project=project, credentials=credentials, _http=None
  File "/tmp/tmpSeKi4K/lib/python3.6/site-packages/google/cloud/client.py", line 227, in __init__
    Client.__init__(self, credentials=credentials, _http=_http)
  File "/tmp/tmpSeKi4K/lib/python3.6/site-packages/google/cloud/client.py", line 132, in __init__
    credentials, _ = google.auth.default()
  File "/tmp/tmpSeKi4K/lib/python3.6/site-packages/google/auth/_default.py", line 321, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
ERROR    2020-04-16 18:16:44,883 app.py:1892] Exception on /products/create [GET]
Traceback (most recent call last):
  File "/tmp/tmpSeKi4K/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/tmp/tmpSeKi4K/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/tmp/tmpSeKi4K/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/tmp/tmpSeKi4K/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/tmp/tmpSeKi4K/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/tmp/tmpSeKi4K/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gabor/my-app/handlers/products.py", line 15, in create
    db = firestore.Client(project='my-project')
  File "/tmp/tmpSeKi4K/lib/python3.6/site-packages/google/cloud/firestore_v1/client.py", line 110, in __init__
    project=project, credentials=credentials, _http=None
  File "/tmp/tmpSeKi4K/lib/python3.6/site-packages/google/cloud/client.py", line 227, in __init__
    Client.__init__(self, credentials=credentials, _http=_http)
  File "/tmp/tmpSeKi4K/lib/python3.6/site-packages/google/cloud/client.py", line 132, in __init__
    credentials, _ = google.auth.default()
  File "/tmp/tmpSeKi4K/lib/python3.6/site-packages/google/auth/_default.py", line 321, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
INFO     2020-04-16 16:16:44,902 module.py:865] default: "GET /products/create HTTP/1.1" 500 290

```

It looks to me that `Client.__init__()` is trying to fetch some Google credentials a few lines before checking the value of `FIRESTORE_EMULATOR_HOST`, but that shouldn't be necessary, or should it? Am I doing something wrong?

**Comment by IlyaFaer** [comment]
> It looks to me that Client.__init__() is trying to fetch some Google credentials a few lines before checking the value of FIRESTORE_EMULATOR_HOST

That's true, credentials designation is the first operation in `Client.__init__()`. When it doesn't got any `credentials` arg, it tries to find credentials through environment variables. Client that is connected to emulator is still client after all, its behavior is as much real-life as it can be.

I assume, you could try to pass a credentials mock into your client, like it's done in Firestore unit tests:
```python
def _make_credentials():
    import google.auth.credentials

    return mock.Mock(spec=google.auth.credentials.Credentials)

db = firestore.Client(project='my-project', credentials=_make_credentials)
```
This way you'll trick the statement which forces the search of credentials with environment variables:
https://github.com/googleapis/python-cloud-core/blob/58c88db4e5c175d52ab796c519dd4a4ed2ec106e/google/cloud/client.py#L131-L132

**Comment by gaborfeher** [comment]
Thanks a lot! Your suggestion works (with the addition of importing mocks and adding parens for the function call) and my problem is solved.

Maybe consider documenting this somewhere more explicitly, because it's understandable how credentials work in production, but that knowledge does not help much about how to get credentials to talk to the emulator.

**Comment by IlyaFaer** [comment]
@BenWhitehead, WDYT? Should we add such a tip into docs?

**Comment by BenWhitehead** [comment]
@IlyaFaer Yeah, I'll create a docs bug and get added to the backlog.
