### ISSUE TITLE
Cannot connect to Firestore Emulator from Separate Container

### ISSUE THREAD

**Issue by taliamax** [googleapis/python-firestore#462]
I'm having problems connecting to the Firestore emulator from a separate docker container, and nothing I've tried (or what issues I've read and attempted to follow, including #335) has worked so far.

#### Environment details

  - OS type and version: macOS Catalina 10.15.7
  - Python version in docker container: 3.9.7
  - Python version in host machine: 3.9.4
  - `google-cloud-firestore` version: 2.2.0
  - Docker version: 3.5.1

Dockerfile for the Firestore container:

```dockerfile
FROM google/cloud-sdk:alpine

RUN apk add --update --no-cache openjdk8-jre

RUN apk --update add npm

RUN gcloud components install cloud-firestore-emulator beta --quiet

RUN gcloud config set project dummy-project-id

CMD gcloud beta emulators firestore start --host-port=0.0.0.0:80
```

Dockerfile for backend (flask) service:

```dockerfile
FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt /app

RUN pip install -r requirements.txt

COPY . /app

RUN pip install -e .

CMD ["./run-backend.sh"]
```

Docker-compose file:
```yaml
version: '3'

services:
    backend:
        build:
            context: ..
            dockerfile: devstack/Dockerfile
        image: backend
        volumes:
            - "../:/app"
        env_file:
            - "../.env"
        networks:
            - app-network
        depends_on:
            - firestore
    firestore:
        image: firestore
        build:
            context: ..
            dockerfile: devstack/firestore.dockerfile
        networks:
            - app-network
        ports:
            - "8080:80"

networks:
    app-network:
        external:
            name: app_router
```

#### Steps to reproduce

I'm able to connect to the physical container through other means, such as by using the Requests library. Here's the shell from inside the `backend` container:

```py
Python 3.9.7 (default, Sep 28 2021, 18:58:25)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get('http://firestore')
<Response [200]>
```

It is also reflected in the logs of the emulator container:

```
firestore_1  | [firestore] Sep 29, 2021 2:42:07 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
firestore_1  | [firestore] INFO: Detected non-HTTP/2 connection.
```

I am likewise able to connect to the emulator through the host Python:

```py
Python 3.9.4 (default, Apr  5 2021, 01:49:30)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ['GCLOUD_PROJECT'] = 'dummy-project-id'
>>> os.environ['FIRESTORE_PROJECT_ID'] = 'dummy-project-id'
>>> os.environ['FIRESTORE_EMULATOR_HOST'] = '127.0.0.1:8080'. # Routed to 8080 on host, but actually running on port 80
>>> from google.cloud import firestore
>>> from google.auth.credentials import AnonymousCredentials
>>> client = firestore.Client(credentials=AnonymousCredentials())
>>> d = client.collection('user').document()
>>> d.get()
<google.cloud.firestore_v1.base_document.DocumentSnapshot object at 0x10efa5e80>
```

This is also corroborated from the Firestore Emulator logs:

```
firestore_1  | [firestore] Sep 29, 2021 2:44:10 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
firestore_1  | [firestore] INFO: Detected HTTP/2 connection.
```

Yet, if I run it through the docker container, once again first confirming that the host is reachable:

```py
Python 3.9.7 (default, Sep 28 2021, 18:58:25)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get('http://firestore')
<Response [200]>
>>> import os
>>> os.environ['GCLOUD_PROJECT'] = 'dummy-project-id'
>>> os.environ['FIRESTORE_PROJECT_ID'] = 'dummy-project-id'
>>> os.environ['FIRESTORE_EMULATOR_HOST'] = 'firestore:80'
>>> from google.cloud import firestore
>>> from google.auth.credentials import AnonymousCredentials
>>> client = firestore.Client(credentials=AnonymousCredentials())
>>> d = client.collection('user').document()
>>> d.get()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 160, in error_remapped_callable
    return _StreamingResponseIterator(
  File "/usr/local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 83, in __init__
    self._stored_first_result = six.next(self._wrapped)
  File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 809, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1632927158.408000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3008,"referenced_errors":[{"created":"@1632927138.183211900","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/usr/local/lib/python3.9/site-packages/google/api_core/timeout.py", line 102, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 164, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ServiceUnavailable: 503 failed to connect to all addresses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/google/cloud/firestore_v1/document.py", line 400, in get
    response_iter = self._client._firestore_api.batch_get_documents(
  File "/usr/local/lib/python3.9/site-packages/google/cloud/firestore_v1/services/firestore/client.py", line 668, in batch_get_documents
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/usr/local/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 204, in retry_target
    six.raise_from(
  File "<string>", line 3, in raise_from
google.api_core.exceptions.RetryError: Deadline of 300.0s exceeded while calling functools.partial(<function _wrap_stream_errors.<locals>.error_remapped_callable at 0x7f54703bf670>, database: "projects/dummy-project-id/databases/(default)"
documents: "projects/dummy-project-id/databases/(default)/documents/user/9MXCQbIhEi2lidkh7pph"
, metadata=[('google-cloud-resource-prefix', 'projects/dummy-project-id/databases/(default)'), ('authorization', 'Bearer owner'), ('x-goog-request-params', 'database=projects/dummy-project-id/databases/%28default%29'), ('x-goog-api-client', 'gl-python/3.9.7 grpc/1.39.0 gax/1.31.1 gapic/2.2.0')]), last exception: 503 failed to connect to all addresses
```

Things I've tried:

- Using the docker network address for the Firestore emulator (by resolving it with `socket.gethostbyname`)
- Using the `internal.docker.host` address
- Changing the port on the Firestore container

**Comment by taliamax** [comment]
Fixed by upgrading to 2.3.3, apparently the version was pinned to `2.2.0`, my bad
