### ISSUE TITLE
Recursive delete fails with no documents

### ISSUE THREAD

**Issue by noxxious** [googleapis/python-firestore#487]
#### Environment details

  - OS type and version: Linux Manjaro, Kernel 5.15 (applies to any)
  - Python version: Python 3.9.6
  - pip version: 20.3.4
  - `google-cloud-firestore` version: 2.3.4

#### Steps to reproduce

  1. have no documents in the collection
  2. call Client.recursive_delete

#### Code example

```python
# example
```

#### Stack trace
```
Traceback (most recent call last):
  File "store.py", line 141, in drop_all
    self.client.recursive_delete( )
  File "google/cloud/firestore_v1/client.py", line 322, in recursive_delete
    return self._recursive_delete(
  File "google/cloud/firestore_v1/client.py", line 343, in _recursive_delete
    for chunk in (
  File "google/cloud/firestore_v1/query.py", line 198, in _chunkify
    last_document = snapshots[-1]
IndexError: list index out of range
```

Adding a simple check on the failing line for an empty array does the trick:
```python
last_document = snapshots[-1] if snapshots else None
```

**Comment by tseaver** [comment]
@noxxious Thanks for the report, and the clear reproduction example.
