### ISSUE TITLE
BlockingIOError: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by simon-liebehenschel** [googleapis/python-firestore#515]
#### Environment details

  - OS Lubuntu 20.04
  - Python version: 3.10.1
  - pip version: 21.3.1
  - `google-cloud-firestore` version: 2.3.4

#### Steps to reproduce

The error is logged always at the application shutdown. In my code, I use `document_ref.collections()`  and `.list_documents()` commands.

#### Stack trace
```
ERROR    asyncio:base_events.py:1729 Exception in callback PollerCompletionQueue._handle_events(<_UnixSelecto...se debug=True>)()
handle: <Handle PollerCompletionQueue._handle_events(<_UnixSelecto...se debug=True>)() created at /usr/local/lib/python3.10/asyncio/selector_events.py:259>
source_traceback: Object created at (most recent call last):
  File "/project/venv/lib/python3.10/site-packages/google/cloud/firestore_v1/async_document.py", line 91, in create
    write_results = await batch.commit(**kwargs)
  File "/project/venv/lib/python3.10/site-packages/google/cloud/firestore_v1/async_batch.py", line 58, in commit
    commit_response = await self._client._firestore_api.commit(
  File "/project/venv/lib/python3.10/site-packages/google/cloud/firestore_v1/async_client.py", line 123, in _firestore_api
    return self._firestore_api_helper(
  File "/project/venv/lib/python3.10/site-packages/google/cloud/firestore_v1/base_client.py", line 154, in _firestore_api_helper
    channel = transport.create_channel(
  File "/project/venv/lib/python3.10/site-packages/google/cloud/firestore_v1/services/firestore/transports/grpc_asyncio.py", line 91, in create_channel
    return grpc_helpers_async.create_channel(
  File "/project/venv/lib/python3.10/site-packages/google/api_core/grpc_helpers_async.py", line 258, in create_channel
    return aio.secure_channel(target, composite_credentials, **kwargs)
  File "/project/venv/lib/python3.10/site-packages/grpc/aio/_channel.py", line 483, in secure_channel
    return Channel(target, () if options is None else options,
  File "/project/venv/lib/python3.10/site-packages/grpc/aio/_channel.py", line 288, in __init__
    self._channel = cygrpc.AioChannel(
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 336, in add_reader
    self._add_reader(fd, callback, *args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 259, in _add_reader
    handle = events.Handle(callback, args, self, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pyx.pxi", line 147, in grpc._cython.cygrpc.PollerCompletionQueue._handle_events
BlockingIOError: [Errno 11] Resource temporarily unavailable
```

**Comment by bitnahian** [comment]
I am able to reproduce the same with multiple asyncio threads calling google firestore with `db.document(f"{path}").get()`.

**Comment by bitnahian** [comment]
https://github.com/grpc/grpc/issues/25364 seems to be the root issue.

**Comment by meredithslota** [comment]
Switched this to a `bug` based on the above discussion; seems like the related issue (linked above) has active discussion and we'll be blocked on fixes in this library until that issue is resolved, so setting the overall priority to p3.

**Comment by daniel-sanche** [comment]
I think this comes down to an unclean exit. It looks like your process is trying to call `batch.commit()` after the shutdown signal has been sent. grpc won't let us create a new channel after a certain point in the shutdown lifecycle, hence the error

To avoid this kind of error, make sure you call `batch.commit()` and close down any other open resources before exiting. Or make use of [context managers](https://github.com/googleapis/python-firestore/blob/a1596a3ea66f4f7c08058134913130266c37c468/google/cloud/firestore_v1/batch.py#L73) wherever possible, to handle clean-up for you automatically

If you think there's still an issue though, feel free to re-open
