### ISSUE TITLE
Firestore client has an OpenSSL issue when used via Firebase Admin Python SDK

### ISSUE THREAD

**Issue by ankitmaloo** [googleapis/python-firestore#534]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-firestore/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Mac OSX Big Sur 11.6
  - Python version: `Python 3.9.10`
  - pip version: `pip 22.0.3`
  - `google-cloud-firestore` version: `Name: google-cloud-firestore
Version: 2.1.1
Summary: Google Cloud Firestore API client library
Home-page: https://github.com/googleapis/python-firestore
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: google-api-core, google-cloud-core, proto-plus, pytz
Required-by: firebase-admin
`

#### Steps to reproduce
Well, I did nothing. Happening automatically. 
  1. Install firebase admin python SDK
  2. Use the JSON way to connect to the server as shown in Docs here: 

#### Code example

```
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore
from firebase_admin import auth

cred = credentials.Certificate("./firebase2.json")   #JSON FIle containing credentials for Firebase
firebase_admin.initialize_app(cred)

db = firestore.client()


docs = db.collection("col").where("username", "==", "access").stream()
```

#### Stack trace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 166, in error_remapped_callable
    return _StreamingResponseIterator(result, prefetch_first_result=prefetch_first)
  File "/usr/local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 89, in __init__
    self._stored_first_result = six.next(self._wrapped)
  File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Getting metadata from plugin failed with error: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))"
	debug_error_string = "{"created":"@1645101847.028328000","description":"Getting metadata from plugin failed with error: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))","file":"src/core/lib/security/credentials/plugin/plugin_credentials.cc","file_line":93,"grpc_status":14}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 168, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ServiceUnavailable: 503 Getting metadata from plugin failed with error: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/a/Desktop/test/noomi_backend/dbutil.py", line 494, in <module>
    getNames("users")
  File "/Users/a/Desktop/test/noomi_backend/dbutil.py", line 302, in getNames
    for doc in docs:
  File "/usr/local/lib/python3.9/site-packages/google/cloud/firestore_v1/query.py", line 208, in stream
    response_iterator = self._client._firestore_api.run_query(
  File "/usr/local/lib/python3.9/site-packages/google/cloud/firestore_v1/services/firestore/client.py", line 965, in run_query
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/usr/local/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 199, in retry_target
    six.raise_from(
  File "<string>", line 3, in raise_from
google.api_core.exceptions.RetryError: Deadline of 300.0s exceeded while calling functools.partial(<function _wrap_stream_errors.<locals>.error_remapped_callable at 0x10412fca0>, parent: "projects/noomi-d9a4e/databases/(default)/documents"
structured_query {
  from_ {
    collection_id: "col"
  }
  where {
    field_filter {
      field {
        field_path: "username"
      }
      op: EQUAL
      value {
        string_value: "access"
      }
    }
  }
}
, metadata=[('google-cloud-resource-prefix', 'projects/noomi-d9a4e/databases/(default)'), ('x-goog-request-params', 'parent=projects/noomi-d9a4e/databases/%28default%29/documents'), ('x-goog-api-client', 'gl-python/3.9.10 grpc/1.37.1 gax/1.26.3 gapic/2.1.1')]), last exception: 503 Getting metadata from plugin failed with error: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by meredithslota** [comment]
I suspect this is an issue in the underlying grpc library, which has been updated (and we've bumped the required versions in releases since this issue was filed). If you're still seeing this issue, can you please share updated repro steps with a newer version of the library?
