### ISSUE TITLE
Using AnonymousCredentials with firestore emulator

### ISSUE THREAD

**Issue by torbenmoeller** [googleapis/python-firestore#546]
Hi,

I have a problem with AnonymousCredentials in combination with firestore emulator and Docker. The firestore is containerized and runs perfectly. The access from my PC works fine. However, if I containerize the application and run the container, then an DefaultCredentialsError is thrown.  One workaround would be to add a service-account.json via GOOGLE_APPLICATION_CREDENTIALS, but I prefer to not have valid service-account.json in my local development environment. 
I stored the complete example [here](https://github.com/torbenmoeller/python-firestore-issue)

#### Environment details

  - OS type and version: python:slim-buster
  - Python version: Python 3.10.2
  - pip version: 21.2.4
  - `google-cloud-firestore` version: 2.3.4
  - `google-auth` version: 2.6.0

#### Steps to reproduce

  1.  docker build -t test .
  2.  docker compose up
  Alternative: docker run --name test --network=python-firestore-issue_issue-network test

#### Code example

```python
from google.auth.credentials import AnonymousCredentials
from google.cloud import firestore

def main():
    db = firestore.Client(credentials=AnonymousCredentials())
    result = db.collection('somecollection').document("3").get()
    print(result.to_dict())
```

#### Stack trace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/__main__.py", line 12, in <module>
    main()
  File "/usr/src/app/__main__.py", line 6, in main
    db = firestore.Client(credentials=AnonymousCredentials())
  File "/usr/local/lib/python3.10/site-packages/google/cloud/firestore_v1/client.py", line 94, in __init__
    super(Client, self).__init__(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/firestore_v1/base_client.py", line 125, in __init__
    super(BaseClient, self).__init__(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/client/__init__.py", line 318, in __init__
    _ClientProjectMixin.__init__(self, project=project, credentials=credentials)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/client/__init__.py", line 266, in __init__
    project = self._determine_default(project)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/client/__init__.py", line 285, in _determine_default
    return _determine_default_project(project)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/_helpers/__init__.py", line 154, in _determine_default_project
    _, project = google.auth.default()
  File "/usr/local/lib/python3.10/site-packages/google/auth/_default.py", line 575, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see h
ttps://cloud.google.com/docs/authentication/getting-started
```

**Comment by torbenmoeller** [comment]
I solved it with the help of the GCP support: 
If you set the FIRESTORE_EMULATOR_HOST, you need credentials as metioned in the description. You also need to set the project via the environment variable GOOGLE_CLOUD_PROJECT. The value should start with "demo-". Setting this variable helped me.
