### ISSUE TITLE
bulk_writer default assignment not working in Client.recursive_delete

### ISSUE THREAD

**Issue by didi-rf** [googleapis/python-firestore#564]
#### Environment details

  - OS type and version: macOS Big Sur, version 11.6.4
  - Python version: Python 3.9.9
  - pip version: pip 21.3.1
  - `google-cloud-firestore` version: google-cloud-firestore==2.4.0

#### Steps to reproduce

  1. call Client.recursive_delete with bulk_writer=None (default value)

#### Code example

```python
    from google.cloud import firestore
    db = firestore.Client('myProject')
    coll = db.collection("a", "b", "c")
    coll.add({"e": "e"},"d")
    db.recursive_delete(coll)
```

#### Stack trace
```
Traceback (most recent call last):
  File "/Users/didi/git/test.py", line 28, in <module>
    test()
  File "/Users/didi/git/test.py", line 25, in test
    db.recursive_delete(coll)
  File "/Users/didi/.virtualenvs/test/lib/python3.9/site-packages/google/cloud/firestore_v1/client.py", line 324, in recursive_delete
    return self._recursive_delete(reference, bulk_writer, chunk_size=chunk_size,)
  File "/Users/didi/.virtualenvs/test/lib/python3.9/site-packages/google/cloud/firestore_v1/client.py", line 348, in _recursive_delete
    bulk_writer.delete(doc_snap.reference)
AttributeError: 'NoneType' object has no attribute 'delete'
```

### Work around
```python
    from google.cloud import firestore
    db = firestore.Client('myProject')
    coll = db.collection("a", "b", "c")
    coll.add({"e": "e"},"d")
    db.recursive_delete(coll, bulk_writer=db.bulk_writer())
```

**Comment by didi-rf** [comment]
Here is the fix PR that should fix this issue: https://github.com/googleapis/python-firestore/pull/565
