### ISSUE TITLE
Increment a field value in google cloud firestore using python

### ISSUE THREAD

**Issue by MishalJasmine** [googleapis/python-firestore#595]
I need to increment a field value using google cloud firestore in a google cloud function. I tried the following methods:

```
from google.cloud.firestore_v1 import transforms
from google.cloud import firestore
users_ref = db.collection('collection_name').document('doc_name')
users_ref.update({
   "femalePatients": transforms.Increment(1)
})
```
Also tried

```
from google.cloud import firestore
users_ref = db.collection('collection_name').document('doc_name')
users_ref.update({
   "femalePatients": firestore.Increment(1)
})
```
The error I am getting is

```
Traceback (most recent call last):
File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 2073, in 
wsgi_app
response = self.full_dispatch_request()
File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1518, in 
full_dispatch_request
rv = self.handle_user_exception(e)
File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1516, in 
full_dispatch_request
rv = self.dispatch_request()
File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1502, in 
dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/layers/google.python.pip/pip/lib/python3.7/site- 
packages/functions_framework/__init__.py", line 171, in view_func
function(data, context)
File "/workspace/main.py", line 212, in function_name
    analytics_calculation(db,patient_data,"global")
File "./lib/common_functions.py", line 157, in analytics_calculation
   "femalePatients": transforms.Increment(1)
File "/layers/google.python.pip/pip/lib/python3.7/site- 
packages/google/cloud/firestore_v1/document.py", line 324, in update
batch, kwargs = self._prep_update(field_updates, option, retry, timeout)
File "/layers/google.python.pip/pip/lib/python3.7/site- 
packages/google/cloud/firestore_v1/base_document.py", line 239, in _prep_update
batch.update(self, field_updates, option=option)
File "/layers/google.python.pip/pip/lib/python3.7/site- 
packages/google/cloud/firestore_v1/base_batch.py", line 142, in update
reference._document_path, field_updates, option
File "/layers/google.python.pip/pip/lib/python3.7/site- 
packages/google/cloud/firestore_v1/_helpers.py", line 941, in pbs_for_update
update_pb.update_transforms.extend(field_transform_pbs)
TypeError: Expected a message object, but got field_path: "femalePatients"
increment {
   integer_value: 1
}
```
The requirements file is as follows:

`google-cloud-firestore>=2.2.0
`
Can I get some help on this?

**Comment by Mariatta** [comment]
Hi @MishalJasmine, I think this issue is the same as #592, where the problem is due to using incompatible version of `protobuf`, we need to use `protobuf<4.0.0`.

Can you try installing google-cloud-firestore v 2.5.1? In this version we pinned the protobuf version to <4.

**Comment by MishalJasmine** [comment]
As you mentioned, I set the google-cloud-firestore  to v2.5.1, but the error still exists.

**Comment by MishalJasmine** [comment]
I set the following versions in the requirements.txt

`google-cloud-firestore==2.5.1
protobuf==3.20.1
google-api-core==2.8.1
`
it resolved all issues.
