### ISSUE TITLE
Severe performance issues and StatusCode.DEADLINE_EXCEEDED running on x64 in GKE versus running on arm64 on Mac M1

### ISSUE THREAD

**Issue by kettenbach-it** [googleapis/python-firestore#738]
Hi!

I experience a massiv performance degradation and DEADLINE_EXCEEDED when running the same program on x64 at GKE versus running in development on arm64 at Mac M1.

The program is pretty simple - it creates two JSON object - one being small, on larger - which need to be written to firestore.

I use a batch request for this:
```
# init Firestore
firestore_collection_A = firestore_client.collection(firestore_collection_A_name)
firestore_collection_B = firestore_client.collection(firestore_collection_B_name)

# Store results in Firestore
firestore_batch = firestore_client.batch()
firestore_batch.set(firestore_collection_A.document(uuid, json_object1)
firestore_batch.set(firestore_collection_B.document(uuid, json_object2)

# Could include other retriable exception types
predicate_504 = retry.if_exception_type(exceptions.DeadlineExceeded)
# Could configure timeout etc.
retry_504 = retry.Retry(predicate_504)

result = firestore_batch.commit(retry=retry_504, timeout=FIRESTORE_COMMIT_TIMEOUT)
```

Here's the timing on arm64:

```
2023-07-18 09:55:41: c1ace5a5-9544-429f-b2d9-df0fdfe0f97d: Adding result A with 567533 bytes in Firestore collection 1
2023-07-18 09:55:41: c1ace5a5-9544-429f-b2d9-df0fdfe0f97d: Adding result B with 1542 bytes in Firestore collection 2
2023-07-18 09:55:41: c1ace5a5-9544-429f-b2d9-df0fdfe0f97d: Start comitting to firestore.
2023-07-18 09:55:45: c1ace5a5-9544-429f-b2d9-df0fdfe0f97d: Done comitting to firestore. Took 3s
```

3seconds: that's perfect fine.

But here's what happens at GKE:

```
2023-07-18 10:16:00: c1ace5a5-9544-429f-b2d9-df0fdfe0f97d: Adding result A with 567533 bytes in Firebase collection 1
2023-07-18 10:16:39: c1ace5a5-9544-429f-b2d9-df0fdfe0f97d: Addingresult B with 1542 bytes in Firebase collection 2
2023-07-18 10:16:39: c1ace5a5-9544-429f-b2d9-df0fdfe0f97d: Start comitting to firestore.
2023-07-18T10:24:59.435186025+02:00 Top-level exception occurred in callback while processing a message
2023-07-18T10:24:59.435286419+02:00 Traceback (most recent call last):
2023-07-18T10:24:59.435298895+02:00   File "/usr/local/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
2023-07-18T10:24:59.435306313+02:00     return callable_(*args, **kwargs)
2023-07-18T10:24:59.435320892+02:00   File "/usr/local/lib/python3.10/site-packages/grpc/_channel.py", line 1030, in __call__
2023-07-18T10:24:59.435330564+02:00     return _end_unary_response_blocking(state, call, False, None)
2023-07-18T10:24:59.435343416+02:00   File "/usr/local/lib/python3.10/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
2023-07-18T10:24:59.435366614+02:00     raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
2023-07-18T10:24:59.435375000+02:00 grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
2023-07-18T10:24:59.435386020+02:00 	status = StatusCode.DEADLINE_EXCEEDED
2023-07-18T10:24:59.435393750+02:00 	details = "Deadline Exceeded"
2023-07-18T10:24:59.435403618+02:00 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2023-07-18T10:24:59.416114717+02:00"}"
2023-07-18T10:24:59.435411199+02:00 >
2023-07-18T10:24:59.435418083+02:00
2023-07-18T10:24:59.435425858+02:00 The above exception was the direct cause of the following exception:
2023-07-18T10:24:59.435449919+02:00
2023-07-18T10:24:59.435457482+02:00 Traceback (most recent call last):
2023-07-18T10:24:59.435464616+02:00   File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 191, in retry_target
2023-07-18T10:24:59.435471506+02:00     return target()
2023-07-18T10:24:59.435478725+02:00   File "/usr/local/lib/python3.10/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
2023-07-18T10:24:59.435485581+02:00     return func(*args, **kwargs)
2023-07-18T10:24:59.435492619+02:00   File "/usr/local/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable
2023-07-18T10:24:59.435534876+02:00     raise exceptions.from_grpc_error(exc) from exc
2023-07-18T10:24:59.435549337+02:00 google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded
2023-07-18T10:24:59.435557020+02:00
2023-07-18T10:24:59.435564299+02:00 The above exception was the direct cause of the following exception:
2023-07-18T10:24:59.435646406+02:00
2023-07-18T10:24:59.435654465+02:00 Traceback (most recent call last):
2023-07-18T10:24:59.435667603+02:00   File "/usr/local/lib/python3.10/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 126, in _wrap_callback_errors
2023-07-18T10:24:59.435676049+02:00     callback(message)
2023-07-18T10:24:59.435684101+02:00   File "/srv/myprogram.py", line 157, in callback
2023-07-18T10:24:59.435696622+02:00     result = firestore_batch.commit(retry=retry_504, timeout=FIRESTORE_COMMIT_TIMEOUT)
2023-07-18T10:24:59.435721480+02:00   File "/usr/local/lib/python3.10/site-packages/google/cloud/firestore_v1/batch.py", line 59, in commit
2023-07-18T10:24:59.435729616+02:00     commit_response = self._client._firestore_api.commit(
2023-07-18T10:24:59.435737924+02:00   File "/usr/local/lib/python3.10/site-packages/google/cloud/firestore_v1/services/firestore/client.py", line 1125, in commit
2023-07-18T10:24:59.435745586+02:00     response = rpc(
2023-07-18T10:24:59.435753113+02:00   File "/usr/local/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 113, in __call__
2023-07-18T10:24:59.435760573+02:00     return wrapped_func(*args, **kwargs)
2023-07-18T10:24:59.435767945+02:00   File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
2023-07-18T10:24:59.435775708+02:00     return retry_target(
2023-07-18T10:24:59.435782960+02:00   File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 207, in retry_target
2023-07-18T10:24:59.435804351+02:00     raise exceptions.RetryError(
2023-07-18T10:24:59.435812599+02:00 google.api_core.exceptions.RetryError: Deadline of 120.0s exceeded while calling target function, last exception: 504 Deadline Exceeded
2023-07-18T10:24:59.435845031+02:00 Traceback (most recent call last):
2023-07-18T10:24:59.436720943+02:00   File "/usr/local/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
2023-07-18T10:24:59.437595123+02:00     return callable_(*args, **kwargs)
2023-07-18T10:24:59.437646717+02:00   File "/usr/local/lib/python3.10/site-packages/grpc/_channel.py", line 1030, in __call__
2023-07-18T10:24:59.438129855+02:00     return _end_unary_response_blocking(state, call, False, None)
2023-07-18T10:24:59.438171683+02:00   File "/usr/local/lib/python3.10/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
2023-07-18T10:24:59.438754726+02:00     raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
2023-07-18T10:24:59.439470183+02:00 grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
2023-07-18T10:24:59.439481648+02:00 	status = StatusCode.DEADLINE_EXCEEDED
2023-07-18T10:24:59.439490304+02:00 	details = "Deadline Exceeded"
2023-07-18T10:24:59.439499411+02:00 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2023-07-18T10:24:59.416114717+02:00"}"
2023-07-18T10:24:59.439507467+02:00 >
2023-07-18T10:24:59.439514364+02:00
2023-07-18T10:24:59.439521284+02:00 The above exception was the direct cause of the following exception:
2023-07-18T10:24:59.439527683+02:00
2023-07-18T10:24:59.439534947+02:00 Traceback (most recent call last):
2023-07-18T10:24:59.439544327+02:00   File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 191, in retry_target
2023-07-18T10:24:59.439551565+02:00     return target()
2023-07-18T10:24:59.439559326+02:00   File "/usr/local/lib/python3.10/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
2023-07-18T10:24:59.439584637+02:00     return func(*args, **kwargs)
2023-07-18T10:24:59.439593012+02:00   File "/usr/local/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable
2023-07-18T10:24:59.439617834+02:00     raise exceptions.from_grpc_error(exc) from exc
2023-07-18T10:24:59.439626581+02:00 google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded
2023-07-18T10:24:59.439633747+02:00
2023-07-18T10:24:59.439640494+02:00 The above exception was the direct cause of the following exception:
2023-07-18T10:24:59.439647300+02:00
2023-07-18T10:24:59.439655446+02:00 Traceback (most recent call last):
2023-07-18T10:24:59.439662992+02:00   File "/srv/myprogram.py", line 205, in <module>
2023-07-18T10:24:59.439676460+02:00     future.result()
2023-07-18T10:24:59.439684267+02:00   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
2023-07-18T10:24:59.439691233+02:00     return self.__get_result()
2023-07-18T10:24:59.439699192+02:00   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
2023-07-18T10:24:59.439720784+02:00     raise self._exception
2023-07-18T10:24:59.439730166+02:00   File "/usr/local/lib/python3.10/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 126, in _wrap_callback_errors
2023-07-18T10:24:59.439737791+02:00     callback(message)
2023-07-18T10:24:59.439745747+02:00   File "/srv/myprogram.py", line 157, in callback
2023-07-18T10:24:59.439752754+02:00     result = firestore_batch.commit(retry=retry_504, timeout=FIRESTORE_COMMIT_TIMEOUT)
2023-07-18T10:24:59.439759974+02:00   File "/usr/local/lib/python3.10/site-packages/google/cloud/firestore_v1/batch.py", line 59, in commit
2023-07-18T10:24:59.439831511+02:00     commit_response = self._client._firestore_api.commit(
2023-07-18T10:24:59.439886335+02:00   File "/usr/local/lib/python3.10/site-packages/google/cloud/firestore_v1/services/firestore/client.py", line 1125, in commit
2023-07-18T10:24:59.440262185+02:00     response = rpc(
2023-07-18T10:24:59.440313078+02:00   File "/usr/local/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 113, in __call__
2023-07-18T10:24:59.440332571+02:00     return wrapped_func(*args, **kwargs)
2023-07-18T10:24:59.440338558+02:00   File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
2023-07-18T10:24:59.440455801+02:00     return retry_target(
2023-07-18T10:24:59.440469251+02:00   File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 207, in retry_target
2023-07-18T10:24:59.440566037+02:00     raise exceptions.RetryError(
2023-07-18T10:24:59.440683930+02:00 google.api_core.exceptions.RetryError: Deadline of 120.0s exceeded while calling target function, last exception: 504 Deadline Exceeded
```

What do we see?
- the firestore_batch.set() for result A takes 39 seconds! Why?? On Mac OS it's only 4 seconds? Is it due to the size of the object?
- After 2 minutes, that whole process fails with 504 Deadline Exceeded

What else might be important and what has beed done?

- Not using batch but creating two separate requests leads to the same problem with the larger of the two requests
- Setting GRPC_TRACE=all and GRPC_VERBOSITY=DEBUG did not give any hints about what is going on
- The firestore ist in nam5 while GKE and my development is in eu-west3. Unfortunately I cannot change the firestore to europe without creating a lot of effort. But since the application is not time critical - I don't care about the insert taking 2,3,4,5,6 seconds - this is not a big problem. I just need to dump some json for later access and want the program to do that in -say - less then 10 seconds

If have no clue what is going on and where to search for the bug? Can you give am hint, please!?

**Comment by kettenbach-it** [comment]
Update: I deployed the same x64 container the has the problems in GKE to an Intel Nuc running docker on premise.
The result is the same as in GKE:

```
2023-07-18 13:14:21: c1ace5a5-9544-429f-b2d9-df0fdfe0f97d: Adding result A with 567533 bytes in Firebase collection 1
2023-07-18 13:14:54: c1ace5a5-9544-429f-b2d9-df0fdfe0f97d: Adding result B with 1542 bytes in Firebase collection 2
2023-07-18 13:14:54: c1ace5a5-9544-429f-b2d9-df0fdfe0f97d: Start committing to firestore.

```

Processing of the 567533 bytes is with 33 seconds pretty slow and then the whole process fails with 504 Deadline Exceeded

Consequences: the reason can't be GKE or any networking issue. It seems to be the x64 binaries of the library....?

**Comment by kettenbach-it** [comment]
Here's the requirements.txt:

```
alembic==1.8.1
aniso8601==8.0.0
apipkg==1.5
apispec==3.3.0
appdirs==1.4.3
astroid==2.4.1
async-timeout==4.0.2
atomicwrites==1.3.0
attrs==19.1.0
beautifulsoup4==4.8.0
cachetools==4.0.0
certifi==2019.9.11
chardet==3.0.4
Click==7.0
coverage==5.1
DateTime==4.3
Deprecated==1.2.13
EditorConfig==0.12.2
elasticsearch==7.17.8
elasticsearch-dsl==7.4.0
execnet==1.7.1
Flask==1.1.2
Flask-Continuum==0.1.7
Flask-Cors==3.0.8
Flask-Migrate==2.5.3
flask-smorest==0.21.0
flask-sqlacodegen==1.1.7
Flask-SQLAlchemy==2.4.1
flask-sqlalchemy-stubs==0.2
future==0.18.2
google-api-core==1.16.0
google-api-python-client==1.8.2
google-auth==1.11.2
google-auth-httplib2==0.0.3
google-cloud-core==1.3.0
google-cloud-pubsub==1.2.0
google-cloud-storage==1.28.0
google-resumable-media==0.5.0
googleapis-common-protos==1.51.0
googlemaps==4.5.3
grpc-google-iam-v1==0.12.3
grpcio==1.42.0
gtin==0.1.13
gunicorn==20.0.4
httplib2==0.17.3
idna==2.8
importlib-metadata==0.23
inflect==2.1.0
isort==4.3.21
itsdangerous==1.1.0
Jinja2==2.10.1
jsbeautifier==1.10.2
jsonschema==3.0.2
lazy-object-proxy==1.4.2
lxml==4.4.1
Mako==1.1.0
MarkupSafe==1.1.1
marshmallow==3.6.0
marshmallow-sqlalchemy==0.23.0
mccabe==0.6.1
more-itertools==7.2.0
mypy-extensions==0.4.3
mysqlclient==2.1.0
ordered-set==4.0.2
packaging==19.2
Pillow==8.1.2
pluggy==0.13.0
protobuf==3.11.3
py==1.8.0
py-healthcheck==1.10.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycountry==19.8.18
PyJWT==2.4.0
PyLaTeX==1.4.1
PyMySQL==0.9.3
pyparsing==2.4.2
pyrsistent==0.15.4
PySocks==1.7.1
pytest==5.4.3
pytest-cov==2.9.0
pytest-flask==1.0.0
pytest-flask-sqlalchemy==1.0.2
pytest-forked==1.1.3
pytest-mock==1.11.1
pytest-pycharm==0.6.0
pytest-xdist==1.30.0
python-dateutil==2.8.0
python-editor==1.0.4
pytz==2019.2
pyzbar==0.1.8
redis==3.5.3
requests==2.22.0
rsa==4.0
ruff==0.0.247
six==1.12.0
soupsieve==1.9.3
sqlacodegen==2.1.0
SQLAlchemy==1.3.17
SQLAlchemy-Continuum==1.3.12
sqlalchemy-filters==0.12.0
sqlalchemy-stubs==0.4
SQLAlchemy-Utils==0.36.5
sqlalchemy2-stubs==0.0.2a22
toml==0.10.0
tomli==2.0.1
typed-ast==1.5.0
types-click==7.1.8
types-cryptography==3.3.21
types-Flask==1.1.6
types-Jinja2==2.11.9
types-MarkupSafe==1.1.10
types-redis==3.5.18
types-requests==2.26.1
types-six==1.16.15
types-SQLAlchemy==1.4.53
types-Werkzeug==1.0.9
typing_extensions==4.4.0
uritemplate==3.0.1
urllib3==1.25.2
uuid==1.30
wcwidth==0.1.7
webargs==6.1.0
Werkzeug==0.16.0
wrapt==1.11.2
zipp==0.6.0
zope.interface==5.4.0
```
