### ISSUE TITLE
firestore.Increment returns error: "TypeError: Not a cmessage"

### ISSUE THREAD

**Issue by akashrajkn** [googleapis/python-firestore#778]
#### Environment details

  - OS type and version: `Ubuntu 22.04`
  - Python version: `3.10.13`
  - pip version: `23.2.1`
  - `google-cloud-firestore` version: `2.11.0`

#### Steps to reproduce 

Run below code.

- I've verified that `duration` is a float. 
- On firebase, `total_duration` field's type is Number

Relevant package versions
```
google-api-core==2.11.0
google-api-python-client==2.86.0
google-auth==2.17.3
google-auth-httplib2==0.1.0
google-cloud-core==2.3.2
google-cloud-firestore==2.11.0
google-cloud-storage==2.8.0
google-crc32c==1.5.0
google-resumable-media==2.4.1
googleapis-common-protos==1.59.0
proto-plus==1.22.2
protobuf==4.22.3
grpcio==1.58.0
grpcio-status==1.58.0
```

#### Code example

```python

db = firestore.client()
doc_ref = db.collection(<collection_id>).document(<doc_id>)
doc_ref.update({'total_duration': firestore.Increment(duration)})
```

#### Stack trace
```
Traceback (most recent call last):
  File "/home/ubuntu/my_server/my_server/api/utils/firebase.py", line 238, in create_or_update_voice_profile_document
    doc_ref.update({'total_duration': firestore.Increment(duration)})
  File "/home/ubuntu/miniconda3/envs/server_env/lib/python3.10/site-packages/google/cloud/firestore_v1/document.py", line 324, in update
    batch, kwargs = self._prep_update(field_updates, option, retry, timeout)
  File "/home/ubuntu/miniconda3/envs/server_env/lib/python3.10/site-packages/google/cloud/firestore_v1/base_document.py", line 239, in _prep_update
    batch.update(self, field_updates, option=option)
  File "/home/ubuntu/miniconda3/envs/server_env/lib/python3.10/site-packages/google/cloud/firestore_v1/base_batch.py", line 141, in update
    write_pbs = _helpers.pbs_for_update(
  File "/home/ubuntu/miniconda3/envs/server_env/lib/python3.10/site-packages/google/cloud/firestore_v1/_helpers.py", line 941, in pbs_for_update
    update_pb.update_transforms.extend(field_transform_pbs)
TypeError: Not a cmessage
```

**Comment by nielsbox** [comment]
Same also have this error and sometimes bumping the version of the library helps. But I'm already at latest now...

**Comment by hansheng654** [comment]
Now i am facing firestore.Increment function does nothing to the actual data field, and no error at all.
I expect better from Google.

**Comment by akashrajkn** [comment]
@hansheng654 Based on this [comment](https://github.com/psf/cachecontrol/issues/292#issuecomment-1533747750), I changed urllib3 package version to `1.26.15`. After this, I don't get the above issue. Maybe this helps you?

**Comment by akashrajkn** [comment]
@kolea2 Thanks for the reply! With version `2.15.0`, I don't get the issue. Feel free to close this issue.

**Comment by kolea2** [comment]
Awesome, thanks for confirming!

**Comment by jstray** [comment]
Getting this same message, version 2.17.0 on this line:

`db.collection("users").document(user_id).set(user_record)`

message:

```
...
        if extractor.has_transforms:
            field_transform_pbs = extractor.get_field_transform_pbs(document_path)
>           set_pb.update_transforms.extend(field_transform_pbs)
E           TypeError: Not a cmessage

/usr/local/anaconda3/lib/python3.12/site-packages/google/cloud/firestore_v1/_helpers.py:723: TypeError
```
