### ISSUE TITLE
Duplicate Symbol Error in google.firestore.admin.v1.Database Proto File

### ISSUE THREAD

**Issue by haimjether** [googleapis/python-firestore#973]
Description:
I encountered a `TypeError` while running tests in my project that uses `google-cloud-firestore`. The error message indicates a duplicate symbol in the proto file:
`TypeError: Couldn't build proto file into descriptor pool: duplicate symbol 'google.firestore.admin.v1.Database.__firstlineno__'`

#### Environment details

  - OS type and version: Official Docker for python:  `python:3.13.0rc3` 
  - Python version: `3.13.0rc3` 
  - pip version: `24.2`
  - `google-cloud-firestore` version: `2.19.0`

#### Steps to reproduce

  1. `docker pull python:3.13.0rc3`
  2. `docker run --rm -it  python:3.13.0rc3 bash`
  3. `python -m pip install google-cloud-firestore`
  4. `python -c "from google.cloud import firestore_admin_v1"`

#### Code example

```python
from google.cloud import firestore_admin_v1
```

#### Stack trace
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from google.cloud import firestore_admin_v1
  File "/usr/local/lib/python3.13/site-packages/google/cloud/firestore_admin_v1/__init__.py", line 18, in <module>
    from .services.firestore_admin import FirestoreAdminClient
  File "/usr/local/lib/python3.13/site-packages/google/cloud/firestore_admin_v1/services/firestore_admin/__init__.py", line 16, in <module>
    from .client import FirestoreAdminClient
  File "/usr/local/lib/python3.13/site-packages/google/cloud/firestore_admin_v1/services/firestore_admin/client.py", line 53, in <module>
    from google.cloud.firestore_admin_v1.services.firestore_admin import pagers
  File "/usr/local/lib/python3.13/site-packages/google/cloud/firestore_admin_v1/services/firestore_admin/pagers.py", line 40, in <module>
    from google.cloud.firestore_admin_v1.types import field
  File "/usr/local/lib/python3.13/site-packages/google/cloud/firestore_admin_v1/types/__init__.py", line 19, in <module>
    from .database import (
        Database,
    )
  File "/usr/local/lib/python3.13/site-packages/google/cloud/firestore_admin_v1/types/database.py", line 34, in <module>
    class Database(proto.Message):
    ...<456 lines>...
        )
  File "/usr/local/lib/python3.13/site-packages/proto/message.py", line 279, in __new__
    file_info.generate_file_pb(new_class=cls, fallback_salt=full_name)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/proto/_file_info.py", line 104, in generate_file_pb
    pool.Add(self.descriptor)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: Couldn't build proto file into descriptor pool: duplicate symbol 'google.firestore.admin.v1.Database.__firstlineno__'
```

**Comment by haimjether** [comment]
Update: happens on released Python 3.13 as well. 

Steps to reproduce:
```docker pull python:3.13.0
docker run --rm -it  python:3.13.0rc3 bash
python -m pip install google-cloud-firestore
python -c "from google.cloud import firestore_admin_v1"
```

**Comment by haimjether** [comment]
Hi, 
currently Python 3.13 support for Firestore is broken because of this issue. 
@daniel-sanche,  would you guys by any chance have a quick fix for it ?

**Comment by daniel-sanche** [comment]
I just tested it, and it seems to be working now. I know there were some recent changes to the shared library code to support 3.13, so it looks like those must have addressed the issue. Thanks for reporting it

**Comment by auvipy** [comment]
in which version this fix was released?
